### ISSUE TITLE
Stuck on Updating...

### ISSUE THREAD

**Issue by YottaBiter** [FishPhd/H2V-Online-Launcher#1]
I Installed a fresh copy of HALO 2 and activated my game. Then i placed this launcher and launched it several times but every time i open it keeps on saying "Updating"
![butt](https://cloud.githubusercontent.com/assets/16973726/13549363/44422b40-e325-11e5-8e8f-8cd7806593bd.png)

**Comment by warmon6** [comment]
Seeing the same issue here. 

First tried it on my current halo 2.

then uninstalled everything halo 2 related (including games for windows live) and then just installed halo 2 (without GFWL and did not activate). 

Problem appears to happen on both.

Well squashing those bugs! Eventually they'll disappear!

**Comment by sicavenged** [comment]
do u have h2v open when updating h2online?? you need h2v open while updating h2online...this is the issue i had...it would be stuck on updating...it was solved by having h2v open while updating h2online

**Comment by warmon6** [comment]
Thanks @sicavenged ! 

That fix the issue! 

Looks like the instructions may need to be changed just a little bit for now to reflect this issue as it currently doesn't mention about starting the game first then this launcher afterwards.

**Comment by FishPhd** [comment]
This is fascinating to me I have no idea why h2v would have to be open. I will look into it.

For now if you are receiving updating issues go here to find out how to install without the launcher https://github.com/FishPhd/H2V-Online-Launcher/releases/tag/0.0.0.0

**Comment by FishPhd** [comment]
I believe this has been fixed in 0.0.0.2 which will be going up on the update sevrer shortly d3319712661b2778b4627e45036321893d2e4a31
