### ISSUE TITLE
(0.0.0.6) Not able to use the h2online Play button

### ISSUE THREAD

**Issue by Grandahl** [FishPhd/H2V-Online-Launcher#14]
Just updated to the newest version. With the newest h2online.exe, the following continues indefinitely:
1. Launch h2online.exe
2. Press the Play button
3. Window opens to locate game EXE
4. Locate it, press open
5. Returned to launcher screen, now with "Game installation verified."

Using the old 0.0.0.5 exe, the launcher updates h2online.
Using halo2, the game starts normally and servers appear.

It is a small issue, but I thought you might like to know. To be clear, everything works except that I cannot use your h2online launcher to play, I must launch from the Halo 2 application.

**Comment by iSupersniper** [comment]
After the game installation verified the button should change to say Play.  did you try opening the application after it verified the game?

**Comment by Grandahl** [comment]
Yes. When trying to open with the H2V launcher, it tried to find the game files again. When trying to open by launching the Halo 2 exe, it worked fine.

**Comment by twist84** [comment]
Try 0.0.0.7

**Comment by Grandahl** [comment]
0.0.0.7 has solved the problem. Thanks!

**Comment by iSupersniper** [comment]
yeah I fixed the issue.  However I backed it back to version 0.0.0.6.  I'm still getting used to GitHub releases.  

thank you for the feedback guys.
