### ISSUE TITLE
H2V: ONLINE

### ISSUE THREAD

**Issue by Plastoma** [FishPhd/H2V-Online-Launcher#15]
I cannot get it to update, I go in and it always gets stuck on updating and I can't figure out why.

**Comment by twist84** [comment]
If you ever get that issue try getting the "[Latest Release](https://github.com/FishPhd/H2V-Online-Launcher/releases/latest)" from Github

**Comment by Plastoma** [comment]
I have tried, I even tried last version. Still wont work

**Comment by pnill** [comment]
There are a few things that could be causing the problem,

1) You're not running the latest version the older versions are known to have a bug which causes updates not to function properly.

2) You're not running the launcher as Administrator.

3) The launcher is not allowed through your firewall.

Please confirm if you've made sure all of the above is not the issue and we'll try troubleshooting further.

**Comment by iSupersniper** [comment]
The launcher requests to be run as administrator regardless so it will always be run as admin.

Plastoma's problem is either 1 or 3.  If it is 3 then you must have some very strict internet firewall protocols.

**Comment by Plastoma** [comment]
I have tried all 3. to help I will tell you what I am doing.

so I run halo2online loads up good it updates then it says "Play" so i click then I do selecting the install path going into the folder and selecting h2online.exe twice then nothing the bar is full and does not move one bit. I thought it would just take time at first so I left for about 20 to 30 minutes and came back to the same thing.

**Comment by pnill** [comment]
Can you provide the contents of h2vlauncher.log please.

**Comment by Plastoma** [comment]
Config loaded
UID: 3038207840421208
Name: Player
Debug: False
Config values failed to load. Resetting...
Latest h2vonline version: 0.0.0.3
Latest launcher version: 0.0.0.6
Local h2vonline version: 0.0.0.3
Local launcher version: 0.0.0.6
Halo 2 version: 0.0.0.0
Cannot locate halo2.exe
Files Needed: 0

**Comment by pnill** [comment]
The only issue I'm seeing is that your halo2.exe was unable to be located, is the launcher in the same folder as your halo2.exe?

**Comment by Plastoma** [comment]
when I downloaded the latest I got H2online.exe runs and gives me xlives h2update gunegame and MF.dll thats it

**Comment by pnill** [comment]
Are you telling me you don't currently have halo 2 installed?,
We don't provide Halo 2 Vista for you.... you must already have the game in order to play this.

**Comment by Plastoma** [comment]
wait, I fixed it I dont know how though but thank you everyone for the help
