### ISSUE TITLE
Can't join games.

### ISSUE THREAD

**Issue by Relcort** [FishPhd/H2V-Online-Launcher#16]
My friend downloaded H2v and H2online but he can't join games, when he tries to join the game says "You can't join this party right now. Please try again later".
What can he do?

**Comment by pnill** [comment]
- Are you on the same network?
- Does he have the game allowed in his firewall?
- Has he tried port forwarding 1000-1001?

**Comment by Relcort** [comment]
No, yes, and no. 
How does he port forward, please? Maybe that will fix it.

**Comment by pnill** [comment]
He has to have access to his router,
http://www.pcworld.com/article/244314/how_to_forward_ports_on_your_router.html

Also please be sure that he's running the latest version of Cartographer and that the text on the top left of the screen is in green and states he's established a connection to the master server.

He may also want to try using a different player name and possibly changing the XUID in the xlive.ini file to a different number (Any number as long as it's the same length).

**Comment by Relcort** [comment]
He is running the latest version of Cartographer and the text is in green and states  he's established a connection to master server, he also tried to change its UID and player name but didn't make it work. 
So we'll try to port forward tomorrow, thanks ;)
