### ISSUE TITLE
Launcher doesn't Verify Install unless H2V closed first

### ISSUE THREAD

**Issue by Clef-0** [FishPhd/H2V-Online-Launcher#17]
If H2V is open, then the launcher is opened, the launcher will offer to close the game, then simply show a Play button to reopen the game, without verifying the installation or offering an update.

**Comment by iSupersniper** [comment]
The launcher only requests to verify the install if it cannot find the game registry key that says it's installed after you hit the play button.  Otherwise it won't show. 

Update will only show on launch

**Comment by iSupersniper** [comment]
Update will only show when the launcher is initially launched after checking if version numbers are different.
