### ISSUE TITLE
Blackscreen on quitting the Game.

### ISSUE THREAD

**Issue by YottaBiter** [FishPhd/H2V-Online-Launcher#2]
Can't even use the Task manager because the Blackscreen is always on top of everything and doesn't go until i shut down my machine.
Windows 10 64bit is my OS

**Comment by FishPhd** [comment]
Im going to add a force kill to the launcher if the game is open. For now just make sure to stick away from borderless windows applications and close the game by exiting the console.

**Comment by pnill** [comment]
This is something related to the way the process terminates with my mod enabled, I'll have to look into why it's happening and possibly remove the console allocation @FishPhd

**Comment by YottaBiter** [comment]
resolved with your Close game button

**Comment by pnill** [comment]
Added a new system which will force quit the game when the DLL is detached the launcher close button should no longer be needed.
