### ISSUE TITLE
The launcher doesn't save Username and UID.

### ISSUE THREAD

**Issue by nukeulater** [FishPhd/H2V-Online-Launcher#20]
The launcher doesn't  save username and I see lots of players with the name "Player".
It's not a big issue,but it happens to me too.
I think it's gonna be easy to fix.

**Comment by FishPhd** [comment]
Yes this is a known issue. I have been busy but ill prob look into moving all that stuff into the exe aswell to have a backup to check.

**Comment by Catarax** [comment]
Even a custom value in xlive.ini is directly reset when starting the launcher.

**Comment by Zetren** [comment]
For the meantime, just launch directly from halo2.exe editing xlive.ini to include your name beforehand. (Protip: set debug log = 1 to hide the watermark in-game.)

**Comment by FishPhd** [comment]
Fixed in fcc698cf34fbe83c7142784b3bfd6177ea7be002

**Comment by Catarax** [comment]
Thanks FishPhd! Is it possible to get a compiled exe with the fixes or a new release (if possible) ?

**Comment by FishPhd** [comment]
Give this a shot https://jii.moe/V1OiwtlQW.exe
