### ISSUE TITLE
The launcher goes in front of the game after "Play"

### ISSUE THREAD

**Issue by Catarax** [FishPhd/H2V-Online-Launcher#21]
When I hit play, i'm still having the launcher over Halo 2 for an unknow reason.

The idea to fix it :
- Auto-close the launcher after "Play" (would be nice)
- Put it as a program in the background of Halo 2

**Comment by Zetren** [comment]
Alt-tab once or twice to hide the launcher, or just click X and Project Cartographer will still work.

**Comment by Catarax** [comment]
Yes, but it's still really annoying for a game, an auto-close feature would be great and by the way, we will get more memory.

**Comment by FishPhd** [comment]
Fixed in fcc698cf34fbe83c7142784b3bfd6177ea7be002
