### ISSUE TITLE
Debug log = 1 doesn't hide in-game watermark

### ISSUE THREAD

**Issue by Catarax** [FishPhd/H2V-Online-Launcher#22]
Using the 0.0.0.7 release, setting debug log = 1 doesn't hide at all the in-game watermark.
I can give my full xlive.ini if necessary.

**Comment by Zetren** [comment]
It does when you are in-game, whether campaign or multiplayer, at least for me. Main menu the watermark still shows.

**Comment by pnill** [comment]
Yes so long as debug =1 and debug log = 1 are set it will be hidden in-game only, it will not be hidden in the menus.

**Comment by Catarax** [comment]
Perfect, sorry for the inconvenience. I think that this option should be enabled by default however.

**Comment by pnill** [comment]
debug log / debug can cause performance issues in some cases which is why it's not enabled by default in the future the text will be hidden by default without debug needing to specified.
