### ISSUE TITLE
Wrong update path issue

### ISSUE THREAD

**Issue by Catarax** [FishPhd/H2V-Online-Launcher#23]
When the 0.0.0.7 release was available, i tried to directly update the from the launcher.
However the download was completely wrong :
![99d2787ab2c243b698b63ca9640dc755](https://cloud.githubusercontent.com/assets/3964507/15607333/3b781096-2412-11e6-8de0-44a47ed7c0de.png)

Instead of going to Halo2\h2online.exe, it tried to update and create Halo2h2online.exe.

No idea if this issue is still present in the current 0.0.0.7 version however, i was probably on 0.0.0.6 or 0.0.0.5.

**Comment by FishPhd** [comment]
This was fixed in 0.0.0.7 but all previous versions (0.0.0.5-0.0.0.6) will have this issue. For now just delete your h2online.exe and redownload.
