### ISSUE TITLE
H2Online crashing

### ISSUE THREAD

**Issue by byebyescaling** [FishPhd/H2V-Online-Launcher#24]
Is it supposed to work on the cracked version? The exe file just crashes on my PC, does nothing. Windows 10.
Here's the log file:

Config loaded
UID: 8414464210530324
Name: Player
Debug: False
Config values loaded

Tried deleting xlive.ini. Did not work. :(

**Comment by pnill** [comment]
Explain 'cracked' version?, and what is crashing Halo2? or the Launcher?

**Comment by byebyescaling** [comment]
By 'cracked', I mean the version that runs without the iso or the CD. And what basically happens is, when I run the H2Online executable, the 'loading' sign appears beside the mouse pointer for two seconds, then nothing happens. So I assume it's crashed.
![image](https://cloud.githubusercontent.com/assets/19755208/15805138/f36f7c52-2b3d-11e6-8a9e-9fb86839b169.png)
![image](https://cloud.githubusercontent.com/assets/19755208/15805140/0c9d5f3c-2b3e-11e6-9825-279d55c7b719.png)

**Comment by pnill** [comment]
Enabled debug(it will produce a more indepth log) on the launcher, and also try running it as administrator.
