### ISSUE TITLE
H2Online stuck on updating

### ISSUE THREAD

**Issue by al1n** [FishPhd/H2V-Online-Launcher#25]
Hi,

So I installed a fresh version of H2V, with the 1.01 patch applied, and whenever I try running h2online.exe, it gets stuck saying Updating. I've reinstalled the game twice now and it still get stuck on Updating.
![ss 2016-06-06 at 05 11 35](https://cloud.githubusercontent.com/assets/19787699/15842008/41638ab2-2c0a-11e6-91aa-3b088042a2e5.png)

**Comment by al1n** [comment]
So I managed to get it properly update, but when I try to join a game I get an error saying: Can't join game different version of Halo 2. When I try opening h2online.exe, it still shows the Update button and gets stuck on Updating...

**Comment by pnill** [comment]
If it's telling you that you have a different version of halo 2 you need to update your halo 2 game, follow the guide on halo2vista.com http://www.halo2vista.com/forums/viewtopic.php?f=33&t=3820
