### ISSUE TITLE
Is 21:9 supported / allowed in matchmaking?

### ISSUE THREAD

**Issue by ghost** [FishPhd/H2V-Online-Launcher#27]
Title. Just curious. Love the work you've done so far. Just don't want to break any rules.

**Comment by FishPhd** [comment]
Not a lot is clear guideline wise as everything is really just boys hosting on some dedis. If it is more comfortable to play that way go for it. I am already aware of people in the community that cheat and use auto hot key binds so no one is going to be witch hunting you.
