### ISSUE TITLE
Launcher crashes before opening on Virtual Machine

### ISSUE THREAD

**Issue by Coke-Daddy-Nut** [FishPhd/H2V-Online-Launcher#29]
I am running Windows 7 on a Parallels Desktop Virtual Machine running on my 2012 MacBook Pro. I run the launcher as an administrator, and before the UI can pop up I get an error message stating that "Halo 2 Online Launcher has stopped working"

The problem details are as follows:
Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: h2online.exe
  Problem Signature 02: 0.0.0.7
  Problem Signature 03: 5747e591
  Problem Signature 04: mscorlib
  Problem Signature 05: 4.0.0.0
  Problem Signature 06: 4ba1da6f
  Problem Signature 07: 11cd
  Problem Signature 08: 89
  Problem Signature 09: System.Windows.Markup.XamlParse
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    4105
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

**Comment by FishPhd** [comment]
Does your vm support .net 4.5.2?

**Comment by Coke-Daddy-Nut** [comment]
I just installed .Net 4.5.2 and it solved my problem, thank you so much!! :D
