### ISSUE TITLE
Halo 2 needs a forced 60fps in Launcher

### ISSUE THREAD

**Issue by ideathsniper** [FishPhd/H2V-Online-Launcher#3]
Hi ty for doing it to H2V community 

 Halo 2 with amd cards needs the command -novsync into the shortcut because with vsync enable the perfomance of the game is bad, i use afterburner to put a fps limit (60fps recomended)  with the command on my h2 shortcut because the game shows 300+ fps ...

i have a question, i need open 1000 to 1006 ports for i host one game? 7 ports  only for this  game? and i open it and tesit it but thats dont work for me ..

**Comment by FishPhd** [comment]
This is actually a larger issue we are working on fixing. Vsync needs to be enabled as well as a 60fps cap to keep the game running at its intended framerate, we are looking into how to do this easily.

**Comment by FishPhd** [comment]
Renamed to "Halo 2 needs a forced 60fps in Launcher"

**Comment by YottaBiter** [comment]
This can be used:http://blog.metaclassofnil.com/?tag=dsfix

**Comment by iSupersniper** [comment]
Ds fix was incorporated in a previous halo 2 launcher specifically for the fps limiting capabilities.  However it would be more beneficial to find a way to do it internally, or program it directly into the launcher without a third party software.

**Comment by YottaBiter** [comment]
Yes @iSupersniper , It will be gr8 to have such features like FPS locking, FOV, MouseThingy, etc. directly programmed into the launcher.
Though @FishPhd , You really do need to implement these features in your launcher, especially Mousethingy. Because everytime we wanna use it, we have to manually open it and inject it to the halo2 process and that SUCKS!

**Comment by pnill** [comment]
A lot of these things, mouse fixes, fps capping etc will be done in the XLive dll not in the launcher... and eventually the launcher shouldn't even be running with the game and should cleanly exit after doing what it needs to.

I've just made a new XLive dll which should properly cap FPS at 60fps and completely fix the issue where the game freezes on exit.

(The new DLL relies on the same method the older versions of DSFix used to cap the FPS)
