### ISSUE TITLE
I CAN'T SEE SERVERS

### ISSUE THREAD

**Issue by ideathsniper** [FishPhd/H2V-Online-Launcher#32]
now i can open the ports for hosting but when i open the game and i search game i cant see servers, any solution? i re download the launcher and i force update too, but nothing happens :/

**Comment by Catarax** [comment]
When you start the game, is it written : Connected to project Cartographer in green at least?

**Comment by ideathsniper** [comment]
i fix it when i restart my computer, no problem now.. but my server dont work :( i have the ports open :(
