### ISSUE TITLE
H2Online launcher crashes attempting to DL 0.0.0.4.zip

### ISSUE THREAD

**Issue by ghost** [FishPhd/H2V-Online-Launcher#33]
here's the crashlog from Event Viewer

Faulting application name: h2online.exe, version: 0.0.0.8, time stamp: 0x57abe482
Faulting module name: KERNELBASE.dll, version: 10.0.14393.0, time stamp: 0x57898e34
Exception code: 0xe0434352
Fault offset: 0x000d96c2
Faulting process id: 0x6cc4
Faulting application start time: 0x01d2062735db9dad
Faulting application path: C:\Users\hp\Downloads\h2online.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c2172457-2885-4b7e-bf83-f73bf6cbfc20
Faulting package full name: 
Faulting package-relative application ID:

is that bad?

**Comment by surprise0451** [comment]
Having the same issue, crashes when attempting to DL 0.0.0.4.zip

**Comment by gjanu** [comment]
Same here, I tried running as admin and running a bunch of different compatibility modes and it still crashes always right when it is finishing downloading the update.

**Comment by FishPhd** [comment]
Rerunning the launcher should sort the problem out. It seems to be a problem with the launcher trying to extract the zip before the download is complete.

**Comment by iSupersniper** [comment]
This should be fixed, re post the issue if it exists.
