### ISSUE TITLE
Launcher crash

### ISSUE THREAD

**Issue by YottaBiter** [FishPhd/H2V-Online-Launcher#36]
Launcher crashes right after the yellow progress bar reaches its end while updating, with a "stopped working" windows error message. Can't update.
EDIT: I'm having this issue with latest launcher released as of now.

**Comment by twist84** [comment]
Did you download the latest version?

**Comment by YottaBiter** [comment]
Yes

**Comment by twist84** [comment]
-Most issues can be solved by deleting "h2online.exe", "xlive.ini", "xlive.dll" from the Halo 2 directory and redownloading the launcher from here: https://github.com/FishPhd/H2V-Online-Launcher/releases/latest
Make sure you run the launcher as Admin and it is not blocked by Windows (Right click, go to Properties, click Unblock)

**Comment by YottaBiter** [comment]
Just now, i got the problem fixed by updating with launcher version 0.0.0.8. It downloaded the needed files. Now i'm gonna use the latest one to play.
