### ISSUE TITLE
Launcher  wont update 

### ISSUE THREAD

**Issue by flygav1** [FishPhd/H2V-Online-Launcher#37]
the launcher exe just keeps saying updating and will not ever finish even after force update

**Comment by iSupersniper** [comment]
When you open the launcher click on the gear icon and tell me your version number

**Comment by lavacraft1** [comment]
I had a similar issue today but instead of not finishing it just crashes. I even tried downloading the launcher again from the website but it just crashes.

**Comment by iSupersniper** [comment]
Can you post your h2launcher.log file contents please

**Comment by lavacraft1** [comment]
> Can you post your h2launcher.log file contents please
where do i find it?

**Comment by pnill** [comment]
Old launcher is no longer in use please use this one,
http://www.halo2vista.com/H2Cartographer/Halo_2_Launcher.exe

**Comment by flygav1** [comment]
I GOT IT TO WORK :)! 
1.reinstalled = didnt work
2. found a new iso (did NOT activate and just installed then ran launcher and worked)
*dont use a serial crack just installing the game and using launcher worked for me. Thanks guys !:)
