### ISSUE TITLE
Can't download launcher

### ISSUE THREAD

**Issue by ghost** [FishPhd/H2V-Online-Launcher#38]
cannot download the launcher it shows some xml files error...........

**Comment by TheSCREWEDSoftware** [comment]
Me to =(

**Comment by OneForAllxd** [comment]
ami tambien me sale ese error de xml files error

**Comment by pnill** [comment]
Old launcher is no longer in use, use this one
http://www.halo2vista.com/H2Cartographer/Halo_2_Launcher.exe
