### ISSUE TITLE
Launcher won't open

### ISSUE THREAD

**Issue by YottaBiter** [FishPhd/H2V-Online-Launcher#39]
Earlier this week, everything worked fine. I was able to use the launcher version 0.1.0.1 and i still have the same version. Now it won't open. I tried to download the latest version but Github's giving an error. I also tried deleting the xlive.ini but no luck. I'm on Win 10 64-bit.

**Comment by pnill** [comment]
The old launcher is no longer in use, grab this one:
http://www.halo2vista.com/H2Cartographer/Halo_2_Launcher.exe
