### ISSUE TITLE
Halo 2 runs at 2 FPS

### ISSUE THREAD

**Issue by MAT-Z8** [FishPhd/H2V-Online-Launcher#6]
When I installed H2V Online worked perfect the first few days. I do not know what happened, I upgraded and reinstalled the graphics drivers, but still the same. When I remove H2V Online, Halo 2 runs at 60+ FPS. Help, thanks.
![halo 21](https://cloud.githubusercontent.com/assets/18063987/14038693/0f007b22-f233-11e5-9df5-8db040135f86.png)

**Comment by pnill** [comment]
Generally this happens when you're unable to connect to the server, I need to add status messages for this...

But I would be sure that the game is allowed through your firewall otherwise the server may currently be down.

**Comment by MAT-Z8** [comment]
Ohh I see.. Firewall it's ok. Now it works fine. It would be nice server status messages. Thank you very much!

**Comment by YottaBiter** [comment]
Oh.. So i raged and literally uninstalled the game for nothing! :D

**Comment by pnill** [comment]
I've added a message to the game which will tell you if you're connected to the master and warn about FPS issues, it should be coming out with the next update.
