### ISSUE TITLE
How do I create a Halo2 dedicated Server

### ISSUE THREAD

**Issue by mabukaone** [FishPhd/H2V-Online-Launcher#8]
I used to have a Halo2 dedicated server when Live was up. I would like to do that again. Is it possible?
Thanks!

**Comment by Grandahl** [comment]
I would like an answer to this as well. There's no way to repopulate a game using only temporary servers.

**Comment by FishPhd** [comment]
It Is possible I am writing up a guide for it

**Comment by mabukaone** [comment]
I really look forward to it!
